sudo: required
dist: trusty

addons:
  apt:
    packages:
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
        # Requirements for Octave
    - octave
    
    
language: python

python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=NEST
    - OMV_ENGINE=PyNEST
    - OMV_ENGINE=PyNN_Brian1
    - OMV_ENGINE=Brian
    - OMV_ENGINE=Brian2
    - OMV_ENGINE=PyNN_NEURON
    - OMV_ENGINE=PyNEURON
    - OMV_ENGINE=PyNN
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=Octave
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=PyLEMS_NeuroML2
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_Brain
    - OMV_ENGINE=jNeuroML_PyNN_NEURON
    - OMV_ENGINE=NetPyNE
    - OMV_ENGINE=jNeuroML_Brain2
    - OMV_ENGINE=pyNeuroML
install:
    - python setup.py install

script:
    - omv list-engines
    - cd utilities/tests
    - omv all -V
    - omv list-engines

